### ISSUE TITLE
Doesn't display integer values

### ISSUE THREAD

**Issue by maximehabibi** [joebeachjoebeach/json-path-finder#1]
Hi, the interpreter does not display integer values from schema. I am using your tool a lot and it would be great if this issue could be resolved.
Please take a look at the associated picture where the values of the fields "recordSetStartNumber" & "recordSetTotalMatches" are not displayed on the right side.
![bugjsonpathfinder](https://user-images.githubusercontent.com/26734424/38345091-744cab52-388d-11e8-802f-a5efcf6d5f63.PNG)

Best regards,
Maxime

**Comment by maximehabibi** [comment]
Looks like it is also the case for false booleans (true booleans are displayed correctly)

Best regards,
Maxime

**Comment by joebeachjoebeach** [comment]
Hey Maxime

Sorry, I only just noticed you opened this issue. Thanks for bringing it to my attention! You're definitely right, and it seems that both `true` and `false` booleans aren't showing up for me, actually. I'll see if I can find some time to work on it. You're also welcome to submit a pull request with a fix if you feel up to it!

I'm glad to hear you're using the tool a lot -- how did you find out about it in the first place?

Joe

**Comment by zmorris** [comment]
@joebeachjoebeach Hah that's funny, I JUST hit the same issue.  I have a ginormous JSON tree to look at and without the integer values, I can't see what I'm doing.  I may try some kind of regex for now to wrap the integers in quotes or something.

Also, if you get time someday, it would be really nice to be be able to click inside the text on the left and go to the corresponding node on the right.  It would save time vs having to turn down the arrows to get to what you want to find.  I'm thinking kind of like the Chrome->right click->Inspect menu that shows the node in the Chrome inspector.  Also a "reveal in text command" would also be nice, to reveal a node's text in the left pane.

**Comment by joebeachjoebeach** [comment]
@zmorris @maximehabibi 

Looks like the fix was actually quite easy. Can you take a look now and let me know if it's working for you? (make sure you do a hard refresh to make sure you're not loading from cache)

@zmorris that's a feature I definitely had in mind back when I started making this. To be honest, I had no clue anybody was using the tool, so I haven't been doing any maintenance. If you add that feature request as a new issue, I'll be more likely to revisit it. Thanks for the feedback!

**Comment by zmorris** [comment]
@joebeachjoebeach hey ya that fixed it.  Congratulations, you win the internet for the day, this is the first time someone has fixed an issue with a repo faster than I could write a regular expression to fix said issue 😲

**Comment by joebeachjoebeach** [comment]
@zmorris good to hear it! Luckily I had some extra time today.

**Comment by maximehabibi** [comment]
@joebeachjoebeach Hey ! Thanks a lot for the fix..! 
I think I found about your tool by googling "JSON path viewer tool" or something like that... I love it :)

Thanks @zmorris aswell
