### ISSUE TITLE
[Feature Request] give back Copying from (right side panel)

### ISSUE THREAD

**Issue by sk8ordi3** [joebeachjoebeach/json-path-finder#17]
removed the option to copy something from the right panel
not the copy button

no longer possible to select any text..

**Comment by joebeachjoebeach** [comment]
hi @sk8ordi3 — could you tell me the following?
- browser
- browser version

The functionality works for me in Safari, Chrome, and Firefox. I'm using `window.navigator.writeText()`, which has had support in major browsers since 2020 at the latest.

**Comment by sk8ordi3** [comment]
i use two browser in Windows

Brave: 1.65.114 Chromium: 124.0.6367.60 (64 bit)
Chrome: 124.0.6367.61 (64 bit)
(both use the newest version)

so in the right panel in your browser it allows you to select anything from the json including the key or the value?

**Comment by joebeachjoebeach** [comment]
@sk8ordi3 I'm so sorry, I totally misread when you said `not the copy button` and thought you meant the copy button wasn't working 🙃

You were right that selecting text wasn't working.

I just pushed a fix for this. Thanks for raising!
