### ISSUE TITLE
Why the path starts with "X." instead of $?

### ISSUE THREAD

**Issue by YehudahA** [joebeachjoebeach/json-path-finder#5]

**Comment by joebeachjoebeach** [comment]
Why `$` instead of `X`? Both are arbitrary. If you provide a reason along with a pull request, I'm open to it.

**Comment by YehudahA** [comment]
```$``` is used by SQL Server, Oracle and more.

**Comment by YehudahA** [comment]
From JsonPath spec: 

> JSONPath assumes the abstract name $ assigned to the outer level object.

https://goessner.net/articles/JsonPath/

**Comment by joebeachjoebeach** [comment]
I'm closing this as I don't think `$` is a great idea. While declining in popularity, jQuery is still used all over the internet, and it is universally used as the `$` variable. I think that would cause a lot more confusion in this app than using `x`.
