### ISSUE TITLE
Spaces are removed in the response body data which are necessary

### ISSUE THREAD

**Issue by Shabir1386** [joebeachjoebeach/json-path-finder#8]
Hi Team,

This is a concern where an additional space been removed in the data corresponding the response body when the path in generated in jsonpathfinder.com
Though original data had an additional space in the context, it is getting removed always.

Could you please fix this as feasible?

Thank you

**Comment by joebeachjoebeach** [comment]
Hello @Shabir1386 — could you please provide an example to reproduce your problem?

**Comment by Shabir1386** [comment]
@joebeachjoebeach Sure. Please find the example as below.

Response Body:
  {
    "group_name": "test group",
    "created_by": {
      "id": "12345",
      "name": "Test name",
      "email": "test@test.com"
      "description": "this is a test description to include  additional  spaces provided intentionally in the data"
    },
    "timestamps": {
      "created_at": "2020-04-08T04:24:25.499+00:00",
      "updated_at": "2020-04-08T04:24:25.499+00:00"
    }
  }

Data in the Path:
description :  this is a test description to include additional spaces provided intentionally in the data

Observation:
Additional spaces after the words include, additional as in the actual description is not maintained in the Path

Hope this helps to understand the concern
Thank you

**Comment by joebeachjoebeach** [comment]
Thanks for the example, @Shabir1386. That's definitely unexpected. I'll take a look at it when I have some free time.

**Comment by Shabir1386** [comment]
You're Welcome @joebeachjoebeach 

Thank you,
Shabir

**Comment by joebeachjoebeach** [comment]
@Shabir1386 This has been fixed. Thanks again for raising it.
3303cf211f0d9184481f52d00a1468a208fb1ef3

**Comment by Shabir1386** [comment]
@joebeachjoebeach  You're Welcome.
Thank you for looking into the concern.

Regards,
Shabir
